### ISSUE TITLE
GPL v3 Code Violation

### ISSUE THREAD

**Issue by GatitoUwU** [NetShieldLLC/plugin#1]
At least give credits if you are going to take code from a [GPL v3](https://github.com/GatitoUwU/DynamicPremium/tree/master?tab=GPL-3.0-1-ov-file#readme) repository: 

[My config manager from 11 months ago](https://github.com/GatitoUwU/DynamicPremium/blob/master/dynamicpremium-commons/src/main/java/im/thatneko/dynamicpremium/commons/config/ConfigManager.java)
["Your config manager"](https://github.com/No-Steal/NetShield/blob/main/velocity/src/main/java/today/netshield/velocity/config/ConfigManager.java)

**Comment by hardcorefactions** [comment]
Hermano, tampoco tienes que hacer un ISSUE sabes? Podías decirme en Discord y ya. Que quieres que ponga?
